### ISSUE TITLE
Account access for Iain

### ISSUE THREAD

**Issue by MeghanHughes** [WhareHauora/App#130]
Kia ora @Br3nda could you please set @iainkirkpatrick  up with account access? The same one you gave me access to if that's ok? 
His email address is iain@rootsystems.nz

**Comment by Br3nda** [comment]
Sure thing. I can make an admin user for you too.

**Comment by Br3nda** [comment]
I've invited Iain to your home's whanau

I also made a full admin account for Janie (I'm improvising - lemme know if you want me to make someone else).
