### ISSUE TITLE
Logout button

### ISSUE THREAD

**Issue by janie-t** [WhareHauora/App#148]
Clicking on this should take user back to Login screen, with the login form cleared.

**Comment by MeghanHughes** [comment]
Currently the log out button is not functioning. 

When the user clicks on the home icon, it acts to log them out, but the app is set up to automatically log the user back in again. This is to avoid having the user sign in every time they open the PWA.

**Comment by Br3nda** [comment]
@meghanhughes I know you described some of this to me at handover. Can you brain dump anything more on how to implement this.

**Comment by janie-t** [comment]
Do you want the Whare Hauora logo to also log a user out?  In current merge request it takes user back to Dashboard.

**Comment by Br3nda** [comment]
No, the dashboard is perfect
