### ISSUE TITLE
Dashboard > My Account > Notifications check boxes

### ISSUE THREAD

**Issue by janie-t** [WhareHauora/App#18]
Checkboxes not appearing

**Comment by MeghanHughes** [comment]
App/components/profile/account/Preferences.js

**Comment by MeghanHughes** [comment]
This issue also refers to [issue34](https://github.com/WhareHauora/App/issues/34)

**Comment by MeghanHughes** [comment]
@janie-t the `-document.js` is documented [here](https://github.com/zeit/next.js/#custom-document) in the next.js docs

**Comment by MeghanHughes** [comment]
`script src="../static/js/modernizr-2.8.3.js" `
?

**Comment by MeghanHughes** [comment]
@janie-t can we close this one too?
