### ISSUE TITLE
New Dev branch desktop view

### ISSUE THREAD

**Issue by MeghanHughes** [WhareHauora/App#39]
![screenshot at 2018-04-18 14-13-16](https://user-images.githubusercontent.com/22287063/38908056-b553ca56-4312-11e8-8ef0-fe03e8dca9c1.png)
![screenshot at 2018-04-18 14-13-07](https://user-images.githubusercontent.com/22287063/38908057-b9b481a8-4312-11e8-83e4-8dc7933f9059.png)

**Comment by janie-t** [comment]
![screen shot 2018-04-18 at 2 48 21 pm](https://user-images.githubusercontent.com/19628512/38909175-a059ef9a-4317-11e8-89d3-aa6ad4281482.png)

**Comment by janie-t** [comment]
At 1600px
![screen shot 2018-04-18 at 2 50 25 pm](https://user-images.githubusercontent.com/19628512/38909237-e3be6fc2-4317-11e8-91c4-59c3b7aaa143.png)
