### ISSUE TITLE
Radio buttons aren't rendering

### ISSUE THREAD

**Issue by MeghanHughes** [WhareHauora/App#43]
https://github.com/WhareHauora/App/blob/c4d7af303b4fa1961e6389883976f9eceef84829/components/profile/setUp/AddRoomModal.js#L15
Really don't understand this. I set up a basic [React Form](https://www.npmjs.com/package/react-form) and I COULD NOT get the radio buttons to render when the other form elements would. Drove me nuts!

**Comment by MeghanHughes** [comment]
Janie has documented checkboxes not rendering either - maybe somehow related? If so it might be likely a `<div class` issue and then something needs fixing in the `style.js`?

**Comment by janie-t** [comment]
Can see the checkbox images render for a second then they disappear - may have connection to icheck? Tried bringing in all scripts but still not working.

**Comment by MeghanHughes** [comment]
Hey @janie-t should we ask for access to the designer for this?

**Comment by MeghanHughes** [comment]
@janie-t can we close this issue? and #54?
