### ISSUE TITLE
whare and room types

### ISSUE THREAD

**Issue by MeghanHughes** [WhareHauora/App#83]
need to add home and room types to api

**Comment by MeghanHughes** [comment]
Hey @Br3nda i think you have added these methods to the api, could you add them to the Postman docs?

**Comment by Br3nda** [comment]
This was merged in here
https://github.com/WhareHauora/wharehauora-server/pull/389

I've added to the postman docs too
Postman is being a bit laggy tonight - not showing all the saves i did, but the home create, home update, room create, room update are all there 
https://documenter.getpostman.com/view/3560032/wharehauora/RVnb9wYN#825ef48a-6ff7-391c-84cc-a611a96db371

There's also room_types and home_types lists.

As per jsonapi spec, you can ask for included associated records, e.g.

https://app.wharehauora.nz/api/v1/homes/1 is details of a home,
and 
https://app.wharehauora.nz/api/v1/homes/1?included=rooms
will return the home *and* it's rooms

https://app.wharehauora.nz/api/v1/homes/1?included=owner,home-type
https://app.wharehauora.nz/api/v1/rooms/6?included=sensors

etc.
